sudo: false
language: elixir
elixir:
  - 1.1.1
  - 1.2.6
  - 1.3.1
otp_release:
  - 18.0
  - 18.1
  - 18.2
  - 19.0
after_script:
  - mix deps.get --only docs
  - mix deps.get --only test
  - MIX_ENV=test mix inch.report
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
matrix:
  exclude:
  - elixir: 1.1.1
    otp_release: 19.0
notifications:
  email:
    on_success: never
    on_failure: always
